# Copyright (c) HashiCorp, Inc.

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: ^docs/.*$
    -   id: trailing-whitespace
        exclude: ^docs/.*$
    -   id: check-added-large-files
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
    - id: pretty-format-golang
-   repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
    - id: go-static-check
      exclude: ^tools/.*$
